version: '3.8'

services:
  codintxt:
    image: tctt
    command: uvicorn tctt.api:api --host 0.0.0.0 --port 8080 --root-path ${ROOT_PATH:-/} --workers ${WORKERS:-1}
    ports:
      - ${PORT:-8080}:8080
    environment:
      - API_KEY=${API_KEY:-123}
      - WORKERS=${WORKERS:-1}
